---

- hosts: all
  become: true
  pre_tasks:

  -  name: Update repository index CentOS
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "CentOS"

  -  name: Install updates Ubuntu
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"


- hosts: ubuntu_elasticstack
  become: true
  roles:
    - ubuntu_elasticstack

- hosts: centos_elasticstack
  become: true
  roles:
    - centos_elasticstack
